In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error,root_mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
import warnings

<ul>
    <li type="I"><strong>Problem : Predicting Used Cars Prices Based Upon their Features : Based On India</strong></li>
    <ul><li>car_name</li></ul>
    <ul><li>brand</li></ul>
    <ul><li>model</li></ul>
    <ul><li>vehicle_age</li></ul>
    <ul><li>km_driven</li></ul>
    <ul><li>seller_type</li></ul>
    <ul><li>fuel_type</li></ul>
    <ul><li>transmission_type</li></ul>
    <ul><li>mileage</li></ul>
    <ul><li>engine</li></ul>
    <ul><li>max_power</li></ul>
    <ul><li>seats</li></ul>
    <ul><li>selling_price</li></ul>
</ul>

In [122]:
model_df = pd.read_csv("Dt/newTransform.csv")
model_df

,car_name,brand,model,seller_type,fuel_type,transmission_type,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
0,65.0,18.0,7.0,1.0,1.0,0.0,9,120000,0.005263,-1.174026,-0.974596,-0.402931,120000
1,34.0,8.0,54.0,1.0,1.0,0.0,5,20000,-0.135088,-0.132468,-0.150115,-0.402931,550000
2,40.0,8.0,118.0,1.0,1.0,0.0,11,60000,-0.468421,-0.132468,-0.196305,-0.402931,215000
3,65.0,18.0,7.0,1.0,1.0,0.0,9,37000,0.219298,-0.649351,-0.494226,-0.402931,226000
4,20.0,6.0,38.0,0.0,0.0,0.0,6,30000,0.543860,0.649351,0.233025,-0.402931,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15405,34.0,8.0,54.0,0.0,1.0,0.0,5,9229,-0.135088,-0.132468,-0.150115,-0.402931,545000
15406,39.0,8.0,117.0,0.0,1.0,0.0,9,10723,0.024561,-0.420779,-0.472286,-0.402931,250000
15407,73.0,18.0,42.0,0.0,1.0,0.0,2,18000,-0.380702,0.324675,0.060046,2.073801,925000
15408,101.0,27.0,77.0,0.0,0.0,0.0,6,67000,0.257895,0.649351,0.346882,-0.402931,425000
15409,27.0,7.0,25.0,0.0,1.0,-1.0,2,13000,-0.292982,0.646753,0.672055,-0.402931,1200000

In [2]:
model_df_org = pd.read_csv("dt/Transformorg.csv")
model_df_org

,car_name,brand,model,seller_type,fuel_type,transmission_type,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
0,65.0,18.0,7.0,1.0,4.0,1.0,9,120000,19.70,796,46.30,5,120000
1,34.0,8.0,54.0,1.0,4.0,1.0,5,20000,18.90,1197,82.00,5,550000
2,40.0,8.0,118.0,1.0,4.0,1.0,11,60000,17.00,1197,80.00,5,215000
3,65.0,18.0,7.0,1.0,4.0,1.0,9,37000,20.92,998,67.10,5,226000
4,20.0,6.0,38.0,0.0,1.0,1.0,6,30000,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15405,34.0,8.0,54.0,0.0,4.0,1.0,5,9229,18.90,1197,82.00,5,545000
15406,39.0,8.0,117.0,0.0,4.0,1.0,9,10723,19.81,1086,68.05,5,250000
15407,73.0,18.0,42.0,0.0,4.0,1.0,2,18000,17.50,1373,91.10,7,925000
15408,101.0,27.0,77.0,0.0,1.0,1.0,6,67000,21.14,1498,103.52,5,425000
15409,27.0,7.0,25.0,0.0,4.0,0.0,2,13000,18.00,1497,117.60,5,1200000

In [3]:
data_dt = pd.read_csv("Dt/Validation.csv")

In [3]:
x = model_df_org.iloc[:,0:12] 
y = model_df_org.iloc[:,[12]]

In [121]:
x.shape[0] != y.shape[0]

False

In [138]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=24)

<h2><strong>Linear Regression</strong><h2>

In [31]:
#LinearRegression
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=24)
lr = LinearRegression()
lr_fit = lr.fit(x_train,y_train)

In [32]:
pre = lr_fit.predict(x_test)
pre

array([[3535221.13643822],
       [ 476142.56730205],
       [2607660.48335803],
       ...,
       [ 592799.26636553],
       [ 685738.90621477],
       [ 688563.98300228]], shape=(3082, 1))

In [35]:
mean_squared_error(y_test,pre)

192575798212.08188

In [7]:
x_test.to_csv("Data/X_test.csv",index=False)
y_test.to_csv("Data/y_test.csv",index=False)

In [150]:
x_train

,car_name,brand,model,seller_type,fuel_type,transmission_type,vehicle_age,km_driven,mileage,engine,max_power,seats
9711,22.0,6.0,44.0,0.0,1.0,1.0,6,75000,25.83,1498,99.00,5
11332,4.0,1.0,0.0,0.0,1.0,0.0,9,86000,16.07,1995,181.00,5
11646,76.0,18.0,88.0,0.0,1.0,1.0,9,112755,22.90,1248,74.00,5
12117,5.0,1.0,1.0,0.0,1.0,0.0,6,65000,14.69,2993,258.00,5
14185,111.0,29.0,45.0,0.0,1.0,0.0,1,29000,12.90,2755,174.50,7
...,...,...,...,...,...,...,...,...,...,...,...,...
3473,77.0,18.0,89.0,1.0,4.0,1.0,8,154000,19.10,1197,85.80,5
8535,96.0,25.0,32.0,0.0,1.0,1.0,7,42514,19.72,1461,108.45,5
14528,101.0,27.0,77.0,0.0,1.0,1.0,9,110000,20.50,1598,103.50,5
899,24.0,7.0,10.0,0.0,4.0,1.0,5,13433,17.80,1198,86.70,5
12706,113.0,29.0,60.0,0.0,1.0,1.0,10,132734,12.80,2494,102.00,8

In [151]:
x_new_tr = x_train.iloc[:,6:12]
x_new_tr

       vehicle_age  km_driven  mileage  engine  max_power  seats
9711             6      75000    25.83    1498      99.00      5
11332            9      86000    16.07    1995     181.00      5
11646            9     112755    22.90    1248      74.00      5
12117            6      65000    14.69    2993     258.00      5
14185            1      29000    12.90    2755     174.50      7
...            ...        ...      ...     ...        ...    ...
3473             8     154000    19.10    1197      85.80      5
8535             7      42514    19.72    1461     108.45      5
14528            9     110000    20.50    1598     103.50      5
899              5      13433    17.80    1198      86.70      5
12706           10     132734    12.80    2494     102.00      8

[12328 rows x 6 columns]

In [190]:
x_new_tr = x_train.iloc[:,6:12]
x_new_tst = x_test.iloc[:,6:12]
poly = PolynomialFeatures(degree=2)
x_tr = poly.fit_transform(x_new_tr)
x_tst = poly.transform(x_new_tst)

In [191]:
cont_cols = x_train.iloc[:,6:12].columns
features = poly.get_feature_names_out(cont_cols)
cont_df_tr = pd.DataFrame(x_tr,columns=features,index=x_new_tr.index)
cont_df_tst = pd.DataFrame(x_tst,columns=features,index=x_new_tst.index)

In [192]:
a = pd.concat([x_train.drop(columns=cont_cols),cont_df_tr],axis=1)
b = pd.concat([x_test.drop(columns=cont_cols),cont_df_tst],axis=1)

In [193]:
lgr = LinearRegression()
lgr.fit(a,y_train)

LinearRegression()

In [194]:
pred = lgr.predict(b)

In [195]:
pred

array([[4577228.90404719],
       [ 338579.99281257],
       [3640520.27073178],
       ...,
       [ 505199.12870453],
       [ 519365.1414192 ],
       [ 488772.33433793]], shape=(3082, 1))

In [196]:
mean_absolute_error(y_test,pred)

181607.5972861161

<h2><strong>Decision Tree</strong><h2>

In [17]:
#DecisionTree
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=24)
dt = DecisionTreeRegressor()
dt_train = dt.fit(x_train,y_train)
dt_train

DecisionTreeRegressor()

In [18]:
pred = dt_train.predict(x_test)

In [19]:
print(r2_score(y_test,pred))
print(mean_squared_error(y_test,pre))
print(mean_absolute_error(y_test,pre))

0.8289020796160295
146121533012.7687
169627.86579587118

In [50]:
#Tuning dt using RandomizedCV
params = {
    'max_depth': [4, 5, 6, 8, 10, None],
    'min_samples_split': [2, 4, 6, 10],
    'min_samples_leaf': [1, 2, 4, 6],
    'max_features': ['sqrt', 'log2', None]
}
random = RandomizedSearchCV(estimator=dt,param_distributions = params,cv=5,n_iter=20,random_state=12,n_jobs=-1,scoring='neg_mean_squared_error')
tune_dt = random.fit(x_train,y_train)
tune_dt

RandomizedSearchCV(cv=5, estimator=DecisionTreeRegressor(), n_iter=20,
                   n_jobs=-1,
                   param_distributions={'max_depth': [4, 5, 6, 8, 10, None],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': [1, 2, 4, 6],
                                        'min_samples_split': [2, 4, 6, 10]},
                   random_state=12, scoring='neg_mean_squared_error')

In [54]:
tune_dt.best_score_

np.float64(-178906591661.59366)

In [46]:
new_dt = DecisionTreeRegressor(min_samples_leaf=6)
new_dt_fit = new_dt.fit(x_train,y_train)
new_dt_fit

DecisionTreeRegressor(min_samples_leaf=6)

In [51]:
new_pred = tune_dt.predict(x_test)
new_pred

array([5910714.28571429,  518412.21374046, 4001071.42857143, ...,
        450411.76470588,  540294.11764706,  488333.33333333],
      shape=(3082,))

In [55]:
#score
mean_squared_error(y_test,new_pred)

122937157515.88953

<h2><strong>RandomForest</strong><h2>

In [47]:
RandomF = RandomForestRegressor(n_estimators=500,min_samples_split=2)
R_fit = RandomF.fit(x_train,y_train)
R_fit

c:\desktop\Used-Car-Prediction\CarsENV\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(min_samples_split=4, n_estimators=500)

In [48]:
R_pre = R_fit.predict(x_test)
R_pre

array([6153538.26349206,  367272.0952381 , 4355552.38968254, ...,
        449823.09444444,  505591.6459596 ,  571070.28571429],
      shape=(3082,))

In [42]:
y_test

       selling_price
3296         6100000
6905          285000
6051         4500000
8265          250000
4304         4200000
...              ...
13311         375000
11710        1100000
6313          420000
966           451000
8323          550000

[3082 rows x 1 columns]

In [46]:
print(mean_squared_error(y_test,R_pre))

73553537910.6815

In [12]:
importance = R_fit.feature_importances_
importance

array([4.38840429e-04, 1.84591319e-04, 2.41263333e-05, 1.13307009e-04,
       2.17824951e-04, 8.84296228e-04, 1.26561987e-04, 5.87704960e-04,
       2.13508962e-04, 3.22349579e-04, 6.18239908e-05, 2.10922657e-04,
       5.11556167e-05, 1.12069379e-03, 2.83625363e-05, 3.84430654e-06,
       2.58179994e-07, 9.75571238e-03, 5.55935776e-08, 2.01626365e-05,
       3.30285429e-05, 6.14836539e-05, 6.74166884e-05, 9.60055214e-06,
       1.47540049e-04, 6.18244742e-08, 3.46463586e-04, 6.17839796e-05,
       1.81814639e-05, 3.69278927e-05, 8.69365127e-06, 1.98225693e-06,
       2.70979333e-04, 7.74667139e-05, 6.04806960e-05, 3.11685386e-06,
       6.37029200e-05, 5.07829551e-06, 1.00775133e-04, 2.12790346e-05,
       8.38406802e-05, 1.52548335e-05, 5.05549130e-06, 9.85584535e-06,
       2.10983499e-04, 2.49920323e-05, 1.81301909e-04, 1.96271729e-05,
       1.38619436e-05, 2.55771479e-06, 9.85530899e-05, 2.65502454e-03,
       1.44285663e-05, 4.10229086e-05, 1.32425123e-04, 3.62881674e-06,
       5.59437653e-06, 8.07676368e-06, 1.36145408e-06, 2.67987870e-06,
       1.40423366e-06, 6.34179278e-05, 1.04848551e-05, 1.36002074e-05,
       1.26841172e-05, 2.91089538e-05, 4.56391993e-05, 1.79612094e-05,
       1.35539803e-05, 7.59871985e-07, 1.60107474e-06, 2.99202880e-07,
       7.75865634e-06, 4.00561083e-05, 2.97726247e-05, 1.01936770e-07,
       3.84079246e-05, 2.71551050e-05, 1.45597153e-05, 2.39892049e-05,
       4.37844817e-06, 4.82546575e-06, 9.36591890e-06, 3.95622588e-05,
       2.81451816e-04, 3.74773441e-05, 5.45123787e-04, 3.19454944e-04,
       5.92021388e-04, 2.32931652e-04, 2.54393060e-04, 1.17789554e-05,
       3.37373604e-06, 5.31179090e-04, 1.50394495e-05, 8.58894559e-06,
       9.43310841e-06, 3.56575717e-06, 7.99879847e-06, 4.08893547e-03,
       1.00669190e-04, 5.33846496e-06, 6.70138712e-05, 3.14407444e-07,
       2.35116411e-06, 1.67348466e-05, 4.95852166e-06, 1.63049451e-04,
       7.51247533e-06, 8.36293037e-06, 4.60998365e-05, 4.73774821e-04,
       3.32496393e-06, 9.25707511e-04, 7.09805045e-06, 1.22208719e-04,
       2.09389784e-05, 6.73833984e-05, 4.62430205e-05, 1.04158776e-05,
       1.51035154e-05, 5.59251199e-04, 7.51775992e-04, 1.69246921e-03,
       3.76310867e-05, 2.42823642e-03, 1.09355042e-08, 1.56906565e-04,
       2.47656631e-04, 1.80824521e-04, 1.26721995e-05, 8.58059780e-06,
       5.05410085e-04, 9.53580395e-05, 1.88575968e-04, 3.14966761e-03,
       2.88581607e-04, 4.67811141e-06, 2.46803548e-04, 7.20552013e-05,
       5.34608625e-06, 4.03189130e-05, 3.62593042e-03, 1.84400721e-04,
       1.40942888e-05, 6.70083170e-04, 1.43915878e-05, 3.81433152e-03,
       3.38190218e-04, 3.13640072e-04, 3.54057102e-04, 1.05623201e-04,
       2.28863140e-04, 4.44576093e-04, 7.57309043e-04, 1.70820534e-04,
       4.44548296e-04, 4.30289467e-04, 2.14116077e-04, 1.23305107e-05,
       2.38852299e-05, 2.50263561e-07, 1.08346513e-05, 1.23460941e-04,
       2.48146628e-05, 2.79725751e-06, 4.06032732e-05, 6.92950422e-06,
       1.02553698e-04, 3.34142612e-04, 2.23798470e-05, 3.66128702e-06,
       2.93971985e-04, 5.56794223e-05, 2.32598206e-05, 4.17221706e-04,
       2.30928513e-05, 1.06727837e-05, 7.86778574e-05, 1.36282427e-05,
       2.31554719e-05, 4.48056853e-06, 1.98347687e-04, 2.91732907e-04,
       6.36701611e-06, 1.17951611e-05, 3.24882900e-07, 1.19884862e-06,
       3.15892595e-07, 7.29915980e-04, 1.99686185e-05, 3.21596588e-05,
       9.59728140e-06, 8.42851991e-05, 6.22318946e-05, 4.60239080e-05,
       2.28725824e-04, 5.69353191e-05, 5.39593515e-04, 9.39713061e-06,
       3.56374549e-04, 5.46600146e-04, 1.99361952e-05, 1.50580548e-02,
       4.36194101e-06, 5.84308136e-03, 2.54177571e-06, 5.15222037e-05,
       1.43328789e-07, 8.02125357e-07, 2.86737750e-05, 1.29694956e-05,
       3.15929547e-05, 6.62855502e-04, 3.46127149e-05, 1.65745845e-06,
       2.18678950e-06, 4.65497652e-06, 7.11705604e-06, 5.75606422e-05,
       8.64016248e-06, 3.06739330e-06, 7.68547740e-05, 4.13129059e-06,
       7.29396455e-05, 1.07142427e-05, 2.01520761e-04, 9.47667876e-05,
       9.70516099e-06, 6.26011165e-05, 5.57577908e-06, 3.45868723e-06,
       3.24947133e-03, 3.97714513e-04, 1.17651918e-07, 1.20117632e-04,
       1.78670593e-04, 4.11241771e-06, 7.29990178e-05, 1.22818500e-04,
       7.32273188e-05, 3.59191448e-05, 2.56019151e-05, 1.03475922e-05,
       7.63182771e-06, 9.16092378e-06, 7.75941240e-06, 6.22469057e-05,
       2.64995715e-05, 7.77533714e-06, 1.05383438e-04, 1.79755157e-05,
       8.49156242e-06, 2.29685650e-05, 1.93035743e-05, 2.05951349e-06,
       1.75468307e-04, 2.85397616e-04, 4.22844197e-05, 2.26417711e-04,
       9.02001677e-05, 1.12345944e-05, 2.04617798e-05, 8.04576153e-06,
       3.67029102e-04, 6.08091098e-06, 9.01927705e-06, 2.59880412e-05,
       5.70811453e-06, 9.74936046e-05, 2.40731441e-05, 7.50578696e-05,
       2.15183436e-07, 1.89760176e-03, 1.41157793e-03, 1.94078339e-05,
       1.92513663e-05, 5.95332837e-04, 8.25552743e-06, 7.44574096e-07,
       7.26051188e-04, 8.40945826e-04, 9.62912881e-04, 1.40222585e-01,
       4.65105525e-02, 2.70417110e-02, 2.01622293e-02, 6.72840340e-01,
       1.82112654e-03])

In [4]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=23)

In [5]:
gb = XGBRegressor(n_estimators=700,learning_rate=0.1)
gb.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=700,
             n_jobs=None, num_parallel_tree=None, ...)

In [113]:
params = {
    'n_estimators':[100,200,300,400,500,600,700,800,900,1000],
    'learning_rate':[1,0.1,0.01,0.001],
    'eval_metric':[mean_absolute_error]

}
tune = RandomizedSearchCV(estimator=gb,param_distributions=params,cv=5,n_iter=10,scoring='neg_mean_absolute_error')
tune.fit(x_train,y_train)

RandomizedSearchCV(cv=5,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraint...
                                          min_child_weight=None, missing=nan,
                                          monotone_constraints=None,
                                          multi_strategy=None, n_estimators=200,
                                          n_jobs=None, num_parallel_tree=None, ...),
                   param_distributions={'eval_metric': [<function mean_absolute_error at 0x000001C4FC9D2AC0>],
                                        'learning_rate': [1, 0.1, 0.01, 0.001],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000]},
                   scoring='neg_mean_absolute_error')

In [6]:
y_test

       selling_price
6699          286000
31            465000
12425         750000
15106         615000
8315          200000
...              ...
6925          375000
10394         270000
14255        1140000
9439          199000
15407         925000

[1541 rows x 1 columns]

In [8]:
f = gb.predict(x_test)
f.astype(int)

array([ 285074,  506628,  739816, ..., 1013109,  247370,  884222],
      shape=(1541,))

In [67]:
f[0].astype(int)

np.int64(6082701)

In [9]:
mean_absolute_error(y_test,f)

90218.2890625

In [58]:
import joblib
joblib.dump(R_fit,"Models/UsedCarRandom_Forest_Model.pkl")

['UsedCarRandom_Forest_Model.pkl']

In [133]:
x_tr,y_tr = train_test_split(model_df_org,train_size=0.8,random_state=12)